##  Linear algebra practice:

In [1]:
import numpy as np
from scipy import linalg

## To get the inverse matrix
## https://docs.scipy.org/doc/scipy/reference/linalg.html

In [2]:
E21=np.array([[1,0,0],[-3,1,0],[0,0,1]])

In [3]:
E21

array([[ 1,  0,  0],
       [-3,  1,  0],
       [ 0,  0,  1]])

In [4]:
print(type(E21))
print(E21.shape)
print(E21.ndim)

<class 'numpy.ndarray'>
(3, 3)
2


In [5]:
linalg.inv(E21)

array([[ 1.,  0., -0.],
       [ 3.,  1., -0.],
       [ 0.,  0.,  1.]])

In [18]:
d=np.array([[1],[1],[1]])
print(d)
print(d.shape)
print(d.ndim)

[[1]
 [1]
 [1]]
(3, 1)
2


## E21 is 3x3,   d  is  3x1 column vector

In [19]:
rr=E21.dot(d)
print(E21)
print(d)
print(rr)

[[ 1  0  0]
 [-3  1  0]
 [ 0  0  1]]
[[1]
 [1]
 [1]]
[[ 1]
 [-2]
 [ 1]]


## now dt is a row vector
## transpose is a ndarray's method

In [20]:
dt=d.transpose()
print(dt)
print(dt.shape)
print(dt.ndim)

[[1 1 1]]
(1, 3)
2


In [21]:
rr=E21.dot(dt)
print(E21)
print(dt)
print(rr)

ValueError: shapes (3,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)